### ISSUE TITLE
Setting service up with Online Trial

### ISSUE THREAD

**Issue by disastor** [MicroFocus/octane-gitlab-service#2]
Hello, I'm attempting to use this service, but I have 2 questions.  

1.) I am doing this with a SaaS trial of Octane and SaaS gitlab.com.  Would this service still work in that configuration?  If so, I'm confused as to what goes in the server.baseUrl property.

2.) When calling `java -jar octane-gitlab-service-1.1.15.jar` the service never connects.  I get a series of errors stating `Domain attribute ".microfocus.com" violates RFC 2109: host minus domain may not contain any dots`.  My entry for octane.location is 'https://almoctane-ams.saas.microfocus.com/ui/?p=my ID/1002'

Thanks for any help you can provide

cc @mstekel

**Comment by mstekel** [comment]
Can you please send me your "application.properties" file (remove any
sensitive information, such as passwords etc., before sending)?

**Comment by disastor** [comment]
@mstekel - thanks for responding.. 
Please find file attached.  I've taken out the Octane client ID and my PAT from GitLab.  I'm also a bit confused as to what to put in the server.baseUrl Property.  Both Octane and GitLab are SaaS versions, so I wasn't sure how to represent this property.  Thanks so much for your help. 

[application.properties.txt](https://github.com/MicroFocus/octane-gitlab-service/files/2923845/application.properties.txt)

**Comment by disastor** [comment]
@mstekel - thanks again for looking into it.  Anything you can tell me about how to properly set this up?

**Comment by mstekel** [comment]
@disastor I'm sorry for the delayed reply. The warning you mentioned was due to a particular cookie on the SaaS server that seems to violate the RFC. Anyway I can see this message is a warning and not an error. Have you eventually ended up with an authentication error or all you see is these warnings, because if no error is shown then these warnings might be OK. I cannot reproduce your issue because I have no Octane instance on this SaaS farm. I need my colleagues' help to create one. Let me create one and get be back to you with my findings. For the meanwhile please let me know if you can see any errors caused by these warnings.

**Comment by mstekel** [comment]
@disastor Thank you for your contribution - you've found a real defect in our SDK. This defect was already fixed in our latest SDK release, however our GitLab solution was based on an earlier release. Changing the dependency to the latest SDK release fixed the problem. Please use our latest release: https://github.com/MicroFocus/octane-gitlab-service/releases/tag/1.1.17

**Comment by disastor** [comment]
@mstekel - thanks so much for this...  I've attempted it with the new version and now I get this error:

`2019-03-11 15:14:13.420 ERROR 33125 --- [ivityWorker-469] c.h.o.i.s.bridge.BridgeServiceImpl       : connection to Octane failed: 404, API changes? version problem?`

**Comment by mstekel** [comment]
@disastor It's supposed to work(I tested it against a similar workspace). Is an HTTP(S) proxy required to connect this machine to the internet? if so - you have to specify the proxy settings in the application.properties file and then restart the service.

**Comment by disastor** [comment]
@mstekel - Thanks for the response.  There's no proxy needed for this particular machine.  I created a new api user with the appropriate CI/CD integration permissions, modified the client ID and secret in the permissions file and ran the command as instructed.   Still getting this response:
`2019-03-12 10:43:27.592 ERROR 55622 --- [ivityWorker-464] c.h.o.i.s.bridge.BridgeServiceImpl       : connection to Octane failed: 404, API changes? version problem?`

Here's the version of ALM Octane I'm using:

Product version:
12.60.35.186
Edition:
Pro
Build time:
Mar 10, 2019 3:36:53 AM
Tenant id:
498582499

Also, I tried to add more API permissions to that user just in case I needed more.. However, I still got the same response.

**Comment by mstekel** [comment]
Hi, can you please generate another API key for me and send it to me by email: mstekel@gmail.com? I'd like to reproduce it locally with my own gitlab server and your octane sharedspace.

**Comment by disastor** [comment]
@mstekel - thanks again.. Email sent.

**Comment by knysh** [comment]
Hello everyone. 
I faced with same issue "connection to Octane failed: 404, API changes? version problem?".
@mstekel, @disastor, Did you fix the issue and if yes what was the solution for you?

**Comment by mstekel** [comment]
Bad configuration
